services:
  - type: web
    name: rag-project
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 8501
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
